### ISSUE TITLE
Running on Windows in a Docker

### ISSUE THREAD

**Issue by manu-sapiens** [kyutai-labs/moshi#94]
### Due diligence

- [X] I have done my due diligence in trying to find the answer myself.

### Topic

The PyTorch implementation

### Question

In case this is useful to someone else as a starting point, I created a Dockerfile and docker-compose.yml files. By recreating those in the moshi directory top level and using:

> docker-compose build
> docker-compose up

I am able to use moshi on my 4090 in Windows 11.
Your milage my vary.

**Dockerfile**
```
FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    git \
    curl \
    build-essential \
    cmake \
    libssl-dev \
    libffi-dev \
    rustc \
    cargo \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip \
    && pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 \
    && pip install --no-cache-dir -r requirements.txt


RUN git clone https://github.com/kyutai-labs/moshi.git

RUN pip install -e "git+https://git@github.com/kyutai-labs/moshi.git#egg=moshi&subdirectory=moshi" \
    && pip install rustymimi

ENV HF_HOME=/models

EXPOSE 8998

CMD ["python", "-m", "moshi.server"]
```

**docker-compose.yml**
```
version: '3.8'

services:
  moshi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8998:8998"
    environment:
      - PYTHONUNBUFFERED=1
      - HF_HOME=/models  # Set the Hugging Face cache path
    volumes:
      - ./models:/models  # Map the local ./models directory to /models inside the container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    restart: unless-stopped
```

UPDATE: I see someone has now created a Pull request for something similar.
